[package]
name = "patina-sci-kernel"
version = "0.1.0"
edition.workspace = true

[features]
default = []
bridge-patina-types = ["dep:patina-types", "dep:nalgebra"]

[dependencies]
patina-types = { path = "../patina-types", optional = true }
nalgebra = { version = "0.33", optional = true }
serde.workspace = true
thiserror.workspace = true
